### ISSUE TITLE
Questions about experimental results and jigsaw_num_splits

### ISSUE THREAD

**Issue by HrealcodeH** [donghao51/MOOSA#2]
Hello, your work is excellent, and I am attempting to reproduce it.

However, I have encountered a problem.
I used the command provided in the README file as follows:
`python train_video_flow_audio_EPIC_MOOSA.py --use_video --use_flow --use_audio -s D2 D3 -t D1 --lr 1e-4 --bsz 16 --nepochs 15 --mask_ratio 0.7 --entropy_min_weight 0.001 --jigsaw_num_splits 2 --datapath my_datapath`

The best results I obtained were:
BestValAcc  0.8290544771446462                                                                        
BestTestAcc  0.5839080459770115                                                                       
**BestTestHscore  0.5360392798690671**                                                                 
BestTestOS  0.44389027431421446                                                                       
BestTestUNK  0.6764705882352942

However, in Table 2 of the paper, the corresponding HOS value should be **56.70**.

Additionally, in the implementation details section of the paper, you mentioned that split_num is 4. So I tried changing jigsaw_num_splits in the above command to 4, but it was too slow to complete the run.

**Comment by donghao51** [comment]
hello, thanks for your question. When there are three modalities, we set jigsaw_num_splits to 2 by default. If we set it to 4, there are too many possible combinations (12!=479 001 600) and make Line https://github.com/donghao51/MOOSA/blob/80092c4ac3998be220e7c8fef540ba2fd9597d09/HAC-rgb-flow-audio/train_video_flow_audio_HAC_MOOSA.py#L113C5-L113C71 extremely slow.

For HOS, did you use the exact env config as we did (i.e., Python 3.10.13, torch 2.3.1+cu121 and NVIDIA GeForce RTX 3090, etc)? If not, you might need to tune mask_ratio (0.3, 0.5) and entropy_min_weight (0.1,0.01) a little bit.

**Comment by HrealcodeH** [comment]
Thank you for your response. The environment I am using is exactly the same as yours, i.e., Python 3.10.13, torch 2.3.1+cu121, and NVIDIA GeForce RTX 3090.
![image](https://github.com/user-attachments/assets/7035c817-6b69-45c7-bcf0-5aa096d80942)
![image](https://github.com/user-attachments/assets/f143ec8d-a917-4df9-8209-d167015e0603)

**Comment by donghao51** [comment]
how about the other packages in requirement.txt? maybe you can try to tune mask_ratio and entropy_min_weight a little bit

**Comment by HrealcodeH** [comment]
The other libraries are the same as well. Thank you for your response, I will try testing other hyperparameters.

**Comment by HrealcodeH** [comment]
> how about the other packages in requirement.txt? maybe you can try to tune mask_ratio and entropy_min_weight a little bit

I achieved the results you reported in your paper by appropriately adjusting these parameters. Thank you very much for your help.
