### ISSUE TITLE
The question regarding the Multimodal Closed-set DG experiment in Table 6 of the paper.

### ISSUE THREAD

**Issue by HrealcodeH** [donghao51/MOOSA#3]
Could you please tell me if the results in Multimodal Closed-set DG correspond to the BestTestAcc output from the train_video_flow_audio_EPIC_MOOSA.py script? If not, could you kindly guide me on how the code should be adjusted to test the Multimodal Closed-set DG results?

**Comment by donghao51** [comment]
hello, it's not. you can follow the codebase in SimMMDG (https://github.com/donghao51/SimMMDG/tree/main) and change the function **train_one_step** accordingly in https://github.com/donghao51/SimMMDG/blob/1f037c42c153bc8c04c0a29bcdfcc9dba742d9a1/EPIC-rgb-flow-audio/train_video_flow_audio_EPIC_SimMMDG.py#L16

based on

https://github.com/donghao51/MOOSA/blob/80092c4ac3998be220e7c8fef540ba2fd9597d09/EPIC-rgb-flow-audio/train_video_flow_audio_EPIC_MOOSA.py#L23

**Comment by HrealcodeH** [comment]
Thank you!
